// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using System.Windows;

[TestFixture]
public class StationTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void staon(string SelfIP,string APMAC,string CamIP, string pass, string gateway, string mask) {
        
            driver.Navigate().GoToUrl("https://192.168.1.20/login.cgi?uri=/");      //Ввод стартовой страницы
            System.Windows.MessageBox.Show("Уберите проверку сертификата в хром и нажмите ок", "Пауза",
                                            System.Windows.MessageBoxButton.OK, System.Windows.MessageBoxImage.Information,
                                            System.Windows.MessageBoxResult.OK, System.Windows.MessageBoxOptions.ServiceNotification);

            driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);      //
            driver.FindElement(By.Id("username")).SendKeys("ubnt");                 //Логин 
            driver.FindElement(By.Id("password")).SendKeys("ubnt");                 //Пароль

            {
                var dropdown = driver.FindElement(By.Id("country"));                  //Выбор страны на первичной странице
                dropdown.FindElement(By.XPath("//option[. = 'Russia']")).Click();
            }
            driver.FindElement(By.Id("agreed")).Click();
            driver.FindElement(By.CssSelector(".submit > input")).Click();
            driver.FindElement(By.CssSelector("a:nth-child(7) > img")).Click();     //Выбор подменю System(7 по порядку)
            driver.FindElement(By.Id("admin_passwd_trigger")).Click();              //Изменение логина и пароля
            driver.FindElement(By.Id("OldPassword")).SendKeys("ubnt");              //
            driver.FindElement(By.Id("NewPassword")).SendKeys(pass);       //
            driver.FindElement(By.Id("NewPassword2")).SendKeys(pass);      //
            driver.FindElement(By.Id("system_change")).Click();                     //Принять 
            driver.FindElement(By.CssSelector("a:nth-child(3) > img")).Click();     //Выбор подменю Wireless(3 по порядку)
            driver.FindElement(By.Id("wds_chkbox")).Click();                        //Флаг WDS
            driver.FindElement(By.Id("essid")).Click();                             //Выбор имени сети
            driver.FindElement(By.Id("essid")).Clear();                             //Очистить поле
            driver.FindElement(By.Id("essid")).SendKeys("ubnt1");                   //Записать новое имя
            driver.FindElement(By.Id("apmac")).Click();                             //Выбор мака точки
            driver.FindElement(By.Id("apmac")).SendKeys(APMAC);                     //Запись мак адресса точки АП
            driver.FindElement(By.Id("security")).Click();                          //Поле  Пароль
            {
                var dropdown = driver.FindElement(By.Id("security"));
                dropdown.FindElement(By.XPath("//option[. = 'WPA2-AES']")).Click(); //Выбор режима защиты WPA2-AES
            }
            driver.FindElement(By.Id("security")).Click();
            driver.FindElement(By.Id("wpa_key")).SendKeys(pass);           //Ввод пароля для соединения АП и СТ
            driver.FindElement(By.CssSelector(".change > input")).Click();          //Принять
            driver.FindElement(By.CssSelector("a:nth-child(4) > img")).Click();     //Выбор подменю Network(4 по порядку)
            Thread.Sleep(1000);
            driver.FindElement(By.Id("mgmtIpAddr")).Click();
            driver.FindElement(By.Id("mgmtIpAddr")).Clear();
            driver.FindElement(By.Id("mgmtIpAddr")).SendKeys(SelfIP);
            driver.FindElement(By.Id("mgmtIpNetmask")).Click();
            driver.FindElement(By.Id("mgmtIpNetmask")).Clear();
            driver.FindElement(By.Id("mgmtIpNetmask")).SendKeys(mask);
            driver.FindElement(By.Id("mgmtGateway")).Click();
            driver.FindElement(By.Id("mgmtGateway")).Clear();
            driver.FindElement(By.Id("mgmtGateway")).SendKeys(gateway);
            driver.FindElement(By.Id("change")).Click();
            driver.FindElement(By.CssSelector("a:nth-child(6) > img")).Click();     //Выбор подменю Services(6 по порядку)
            driver.FindElement(By.Id("pwdogStatus")).Click();
            driver.FindElement(By.Id("pwdogHost")).Click();
            driver.FindElement(By.Id("pwdogHost")).SendKeys(CamIP);
            driver.FindElement(By.CssSelector(".change > input")).Click();
            driver.FindElement(By.Id("apply_button")).Click();
            Thread.Sleep(10000);
            driver.Close();
            TearDown();
    }
}
